package org.HearthStone.personnages.monstres_classes;

public enum NomMonstre {
    Thunderfoot,
    Shadowfiend,
    Gloomface,
    Firefang,
    Frostbite,
    Venomstrike,
    Dreadclaw,
    Nightshade,
    Doombringer,
    Skullcrusher,
    Bloodfang,
    Darkheart,
    Soulreaper,
    Bonecruncher,
    Deathwing,
    Hellfire,
    Shadowfang,
    Blackthorn,
    Grimshadow,
    Vilespawn,
    Rotgut,
    Corpsegrinder,
    Plaguebearer,
    Voidwalker,
    Doomhammer,
    Terrorclaw,
    Dreadscale,
    Nightstalker,
    Venomspine,
    Frostfire,
    Shadowstrike,
    Gloomfang,
    Thunderclaw,
    Deathbringer,
}
